#!/usr/bin/env node
/** Write web/.env.local from repo root env (.env.local preferred over .env). */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const rootDir = resolve(import.meta.dirname, "..");

function loadEnvFile(path) {
  if (!existsSync(path)) return null;
  return Object.fromEntries(
    readFileSync(path, "utf8")
      .split("\n")
      .filter((line) => line && !line.startsWith("#"))
      .map((line) => {
        const idx = line.indexOf("=");
        return [line.slice(0, idx), line.slice(idx + 1)];
      })
      .filter(([key]) => key),
  );
}

const env =
  loadEnvFile(resolve(rootDir, ".env.local")) ??
  loadEnvFile(resolve(rootDir, ".env"));

if (!env) {
  console.error("Missing .env or .env.local — copy .env.example first.");
  process.exit(1);
}

const baseUrl = (env.SUPABASE_URL ?? "https://wchzccrcqlxgsftjbpgn.supabase.co").replace(
  /\/$/,
  "",
);
const functionsUrl = env.VITE_FUNCTIONS_URL ?? `${baseUrl}/functions/v1`;

const body = `# Auto-generated by scripts/write-web-env.mjs
VITE_FUNCTIONS_URL=${functionsUrl}
VITE_KFZ_API_KEY=${env.KFZ_API_KEY ?? env.VITE_KFZ_API_KEY ?? ""}
`;

const outPath = resolve(rootDir, "web/.env.local");
writeFileSync(outPath, body);
console.log(`Wrote ${outPath}`);
