#!/usr/bin/env node
/**
 * Write Vite env files from repo root .env.local (dev) or .env (prod build).
 *
 *   KFZ_ENV=local → web/.env.local
 *   KFZ_ENV=prod  → web/.env.production.local
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { loadEnvTarget } from "./lib/load-env.mjs";

const rootDir = resolve(import.meta.dirname, "..");
const target = process.env.KFZ_ENV;

if (target !== "local" && target !== "prod") {
  console.error('KFZ_ENV must be "local" (web:dev) or "prod" (web:build).');
  process.exit(1);
}

const envPath = loadEnvTarget(target);

const baseUrl = (process.env.SUPABASE_URL ?? "https://wchzccrcqlxgsftjbpgn.supabase.co").replace(
  /\/$/,
  "",
);
const functionsUrl = process.env.VITE_FUNCTIONS_URL ?? `${baseUrl}/functions/v1`;

const body =
  target === "local"
    ? `# Auto-generated by scripts/write-web-env.mjs (${target})
VITE_FUNCTIONS_URL=${functionsUrl}
VITE_KFZ_API_KEY=${process.env.KFZ_API_KEY ?? process.env.VITE_KFZ_API_KEY ?? ""}
`
    : `# Auto-generated by scripts/write-web-env.mjs (${target})
# Household key is NOT baked into prod builds — enter once in the PWA.
VITE_FUNCTIONS_URL=${functionsUrl}
`;

const outName = target === "local" ? ".env.local" : ".env.production.local";
const outPath = resolve(rootDir, "web", outName);
writeFileSync(outPath, body);
console.error(`→ ${target} PWA env: ${outPath} (from ${envPath})`);
